# Generated by Django 3.2 on 2021-06-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjournment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CaseFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HCCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('pucca', models.DateField()),
                ('kuccha', models.DateField()),
                ('judges', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LCCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('pucca', models.DateField()),
                ('kuccha', models.DateField()),
                ('judges', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SCCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('pucca', models.DateField()),
                ('kuccha', models.DateField()),
                ('judges', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_copies', models.CharField(max_length=255)),
                ('lc_copies', models.CharField(max_length=255)),
                ('adjournment', models.CharField(max_length=255)),
                ('case_filing', models.CharField(max_length=255)),
                ('cm', models.CharField(max_length=255)),
                ('hc_copies', models.CharField(max_length=255)),
            ],
        ),
    ]
